dist: trusty
language: cpp
sudo: required

addons:
  apt:
    sources:
      - george-edison55-precise-backports
    packages:
      - cmake-data
      - cmake

script:
 - ls -ll
 - chmod a+x ../Hook
 - ls -ll
 - su
 - mkdir build
 - ls -ll
 - cd build
 - ls -ll
 - cmake ..
 - ls -ll
 - make
 - ls -ll
 
